"""Export the show's sound library as WAV files (for CapCut, Confessionals, trailers...).

  python pipeline/sound_kit.py            # -> sound_kit/*.wav (24 kHz mono, peaks at -1 dBFS)

Every file is generated by pipeline/sounds.py, which is deterministic, so re-running this
always produces the same files, and they match what the episodes use.
"""
import os

import numpy as np
import soundfile as sf

import sounds as snd
from common import SHOW_DIR

OUT = os.path.join(SHOW_DIR, "sound_kit")


def typing_line(text="Where were you on the night of June 13th?", span=1.44):
    """A typed interviewer question exactly as the question cards play it: keys, then the bell."""
    y = np.zeros(int((span + 1.6) * snd.SR))
    for j, ch in enumerate(text):
        if ch != " ":
            key = snd.typewriter_click(j) * 10 ** ((snd.LEVELS["typewriter"] + snd.typewriter_gain(j)) / 20)
            i = int((0.15 + span * j / len(text)) * snd.SR)
            y[i: i + len(key)] += key
    ding = snd.carriage_ding() * 10 ** (snd.LEVELS["ding"] / 20)
    i = int((0.15 + span + 0.05) * snd.SR)
    y[i: i + len(ding)] += ding[: len(y) - i]
    return y


def theme(seconds=60.0):
    bed = snd.motif_bed(seconds)
    fade = np.ones(len(bed))
    k = int(3.0 * snd.SR)
    fade[int(seconds * snd.SR) - k: int(seconds * snd.SR)] = np.linspace(1, 0, k)
    fade[int(seconds * snd.SR):] = 0
    return (bed * fade)[: int(seconds * snd.SR)]


KIT = {
    "theme_60s": lambda: theme(60.0),
    "sting_title": lambda: snd.sting(5.0),
    "sting_end": lambda: snd.sting(6.0),
    "sting_soft": lambda: snd.sting(4.0),
    "camera_shutter": snd.shutter,
    "typewriter_key": snd.typewriter_click,
    "typewriter_question": typing_line,
    "typewriter_bell": snd.carriage_ding,
    "wind_20s": lambda: snd.wind(20.0),
    "wind_chimes_20s": lambda: snd.chimes(20.0),
    "night_crickets_20s": lambda: snd.crickets(20.0),
    "doorbell_glitch": snd.glitch,
}


def main():
    os.makedirs(OUT, exist_ok=True)
    for name, make in KIT.items():
        y = make()
        y = y / (np.max(np.abs(y)) + 1e-9) * 10 ** (-1 / 20)
        path = os.path.join(OUT, f"{name}.wav")
        sf.write(path, y, snd.SR, subtype="PCM_16")
        print(f"{name:22s} {len(y) / snd.SR:5.1f}s")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
